class AppStrings {
  static const String checkIn = "Check In";
  static const String checkOut = "Check Out";
  static const String checkInPrompt = "You haven't Punched-in yet";
  static const String goodMorning = '"Good Morning ,';
  static const String overview = "Overview";
  static const String dashboard = "Dashboard";
  static const String developerTitle = "Full-stack Developer";
  static const String home = "Home";
  static const String history = "History";
  static const String leave = "Leave";
  static const String profile = "Profile";
  static const String deadline = "Deadline";
  static const String project = "Project";
  static const String myTasks = "My Tasks";
  static const String taskTracker = "Task Tracker";
  static const String ongoingPending = "Ongoing & Pending";
  static const String workSummary = "Work Summary";
  static const approved = 'approved';
  static const pending  = 'pending';
  static const rejected = 'rejected';
  static const upcoming = 'upcoming';
  static const String attendance = "Attendance";
  static const String leaveStatus = "Leave Status";
  static const String holidayList = "Holiday List";
  static const String payslip = "Payslip";
  static const String reports = "Reports";

  static const uiuxDesign = "UI/UX Design Implementation";
  static const responsiveDesign = "Responsive Design";
  static const backendDevelopment = "Back-end Development";
  static const serverSideLogic = "Server-side Logic";

  // Task Statuses
  static const ongoingTask = "Ongoing Task";
  static const pendingTask = "Pending Task";

  // Common Labels
  static const status = "Status: ";
  static const priority = "Priority ";
  static const assignedDate = "Assigned date: ";
  static const dueDate = "Due date: ";
  static const daysRemaining = "days remaining";

  // Button Labels
  static const makeAsDone = "Make as Done";
  static const markAsDone = "Mark as Done";
  static const startTask = "Start task";
  static const start = "Start";
  static const update = "Update";
  static const complete = "Complete";

  // Progress and Actions
  static const notStarted = "Not Started";
  static const inProgress = "In Progress";
  static const completed = "Completed";
  static const overdue = "Overdue";

  static const String appName = 'Ziya Attend';
  static const String tagline = 'Smart Attendance Maintainer';
  static const String loginTitle = 'Login Successful';
  static const String loginWelcome = 'Welcome back, ';
  static const String loginFailed = 'Login Failed';
  static const String continueBtn = 'Continue';
  static const String rememberMe = 'Remember me';
  static const String forgetPassword = 'Forget Password?';
  static const String loginBtn = 'Log In';
  static const String noAccount = "Don't have account? ";
  static const String signUp = 'Sign Up';
  static const String fullName = 'Full Name';
  static const String email = 'Email';
  static const String password = 'Password';
  static const String success = 'Success';
  static const String accountCreated = 'Account created successfully!';
  static const String error = 'Error';
  static const String passwordMin = 'Minimum 8 characters';
  static const String passwordNumber = 'At least 1 number';
  static const String passwordLetter = 'At least 1 letter (A-Z or a-z)';
  static const String signUpPrompt = 'Create an account and enjoy all services';
  static const String haveAccount = 'Already Have account? ';
  static const String login = 'Log In';


  // Misc
  static const assignedByOptional = "Assigned By\n(optional)";


  static const String appName1 = "Ziya Academy";
  static const String subTitle1 = "KEY TO SUCCESS";
  static const String payslipForMonth = "Payslip for month";
  static const String empSummary = "Employee Summary";
  static const String empName = "Employee Name";
  static const String designation = "Designation";
  static const String employeeId = "Employee ID";
  static const String dateOfJoining = "Date of Joining";
  static const String payPeriod = "Pay Period";
  static const String payDate = "Pay Date";
  static const String empnetPay = "Employee Net Pay";

  static const String paidDays = "Paid Days";
  static const String lopDays = "LOP Days";
  static const String pfAc = "PF A/C";
  static const String uan = "UAN";

  static const String earning = "Earnings";
  static const String deduction = "Deductions";
  static const String amount = "Amount";
  static const String ytd = "YTD";

  static const String grossEarning = "Gross Earnings";
  static const String totalDeduction = "Total Deductions";
  static const String totalNetPayable = "Total Net Payable";
  static const String gtDeduction = "Gross Earnings - Total Deductions";

  static const String amountInWords = "Amount in Words:";
  static const String sal = "Rupees Forty Five Thousand Only";

  static const String autoGeneratedTxt = "This is a system generated payslip, signature not required.";
  static const String downloadPayslip = "Download Payslip";
  static const String monthlyPayslipHistory = "Monthly Payslip History";

  static const String month = "Month";
  static const String netPay = "Net Pay";
  static const String action = "Action";

  // Report page headings
  static const String totalWorkingDays = 'Total Working Days\n(This Month)';
  static const String totalHoursWorked = 'Total Hours Worked';
  static const String tasksCompleted = 'Tasks Completed';
  static const String avgDailyHours = 'Average Daily Hours';

  static const String dailyLogTitle = 'Daily Clock-In/Out Log';
  static const String reportChartTitle = 'Attendance';

  // Table headers
  static const String date = 'Date';
  static const String totalHours = 'Total Hrs';


  // Chart legend
  static const String present = 'Present';
  static const String absence = 'Absence';
  static const String avgHrs = 'Avg hrs';

  // Units
  static const String days = 'days';
  static const String hrs = 'hrs';
  static const String hrsPerDay = 'hrs/day';
  static const String thisMonth = 'this month';

  static const String searchReportsHint = 'Search reports...';
  static const String searchHistory = 'Search History';



}
