// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPsDLuv51abF7nQigyETBoUQ8kGWdRs1U',
    appId: '1:228437662713:web:f9a7cbfe9808660467bb28',
    messagingSenderId: '228437662713',
    projectId: 'ziyauser',
    authDomain: 'ziyauser.firebaseapp.com',
    storageBucket: 'ziyauser.firebasestorage.app',
    measurementId: 'G-NH88FGCJR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATRdCEppCIFyRmKlntB6usJ_JhCkmTfp0',
    appId: '1:228437662713:android:847c32b5c6442c2167bb28',
    messagingSenderId: '228437662713',
    projectId: 'ziyauser',
    storageBucket: 'ziyauser.firebasestorage.app',
  );
}
